// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: updateuser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET hashed_password = $2, email = $3, updated_at = NOW()
WHERE users.id = $1
`

type UpdateUserParams struct {
	ID             uuid.UUID
	HashedPassword string
	Email          string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.ID, arg.HashedPassword, arg.Email)
	return err
}
